### ISSUE TITLE
Server crashes on launch if you change the generator options AT ALL. (even the example in pocketmine.yml the file crashes it lol)

### ISSUE THREAD

**Issue by EPICSAURUSS** [freehij/Festival#16]
Festival Crash Dump Mon Jul 28 00:25:46 CDT 2025

Error: Uncaught Error: Call to undefined method pocketmine\level\generator\GeneratorRegisterTask::getTerminationInfo() in C:\Users\epics\Downloads\Festival-main (2)\Festival-main\src\pocketmine\scheduler\AsyncPool.php:155
File: /src/pocketmine/scheduler/AsyncPool
Line: 155
Type: E_ERROR

Code:
[146] 		foreach($this->tasks as $task){
[147] 			if($task->isGarbage() and !$task->isRunning()){
[148] 
[149] 				if(!$task->hasCancelledRun()){
[150] 					$task->onCompletion($this->server);
[151] 				}
[152] 
[153] 				$this->removeTask($task);
[154] 			}elseif($task->isTerminated()){
[155] 				$info = $task->getTerminationInfo();
[156] 				$this->removeTask($task, \true);
[157] 				$this->server->getLogger()->critical("Could not execute asynchronous task " . (new \ReflectionClass($task))->getShortName() . ": " . $info["message"]);
[158] 				$this->server->getLogger()->critical("On ".$info["scope"].", line ".$info["line"] .", ".$info["function"]."()");
[159] 			}
[160] 		}
[161] 
[162] 		Timings::$schedulerAsyncTimer->stopTiming();
[163] 	}
[164] }
[165] 

Backtrace:
#0 (): pocketmine\Server->crashDump()

Festival version: 1.0 #0 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT EPICSAURUS 10.0 build 26100 (Windows 10) AMD64
PHP Version: 8.0.28
Zend version: 4.0.28
OS : WINNT, win

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfQt32kjW4F+pdc/5xpkxhIff2cxZjHFCBwwDOEl3M8sppALUFpJaD9vk2/nve++tKqkkBLbT
Pd/unp2cbiNV3Xrduu966D8PYmctDi7rZyfN0/Na8/j06ECEoR8eXP7nQbwJIOugM+uMRoPRwdHB
WkQRX2LanWfxZLmKWQeBL1mbuy6LfZZ4tlg4nrDZWsQr32aBb92LeA1J06krHoQ7nS6FJ0Ie++F0
+kE/jsTSiWIRTnh0f3m5FPFEhFCIx47vdb2Ff/iGOR5rX06nd5EIo+lUBI4FP9f+o+f63IbHGxHF
zgN3K2sOoIeNN4Wk6TQKrenU7FBkrYSduAJ60oo2njX0fbcarILL+skJDHfhuDjWt1DubVbsbVrq
bVoIgF3IOsCC/zw6CNxk6XgHlwvuRuLowPJtgfisH59CddN4Gi/8UHBrdfineOVElb/FMOqI8Yj9
CZ/e/CdUVz8+U7DT2FkcUkblb070gYdzmALAB/ds9t/S9FHieY63PHyjSp9DaXq4SKuhinSJFY/a
3LOE6wobyupyJzUDfBorYN9r++vAFTgbus8wDQ8ifPOOStWNUv+klIZq/6RpZKmioVj7DwKnWo5L
VXKcQv5TAN7MUWtqEHba0ROzXgdIhL1nCr6MfGQTp8935ohNp3GYCFXibLuEHDk10/OXSxEevqn8
zQqd2LG4ezg9aPuJazPPj5l4ElYSC5hZoJNV6Ht+EjFshE0PWJUdeuIRWhuJhSss7Grb5VGkcPKG
Ghiv/DC+5Wuc8CqUupQlacC/TDVDTg/+obp7/vruDjyos6prjCw/wPqq04MjhjRtZuI75DHKNNIX
iUf9l+UO30wPVHcy4iOqONXUJd/qikZOGyp54sCkLaPLyz+lPEYsBuk4gij2Awmi5vNUEpesDclH
PgFpeInrAiPGIbeA9X45+KHGDt9c5qTRWOHFCnm0uk7WweGbg38cHUjp5CK/QnYEo4J669Ua1DxP
HNc+uKwBg4d+7FvA95eNs6MDHjgEU28Q2NKJ4bX2wn9QIOT3rjPHMtUzqiHxOArlgy+OZ/uPEbud
sM6w2x637kZ3Y1avVWuM+sIap/UajEzD1WtvWKt/DaiALq4CqOG8Wqs2zuH1m/Cg6wfH+h2yZ36E
bXRvbyeQQC+PILVS+QUJvwBCAh5Cb0A2q3dJT1VAQSDC2BFY7odh+sbavrdwlgyF5zScej/0fY/9
mLiscc5qtcvGyeXxCWtfT1ij1jhBAEWfOOT3S9/3YKqdeGPkBMAC7+sX9WYDE9fAr+Gm4gIdxO8b
tePzPqYuOabb4n2dYPhTJXD5Bvr8vkk1BfzRq+CsSUZ7XyG4x5UTC6gqit/7iwWmCI/PXVH5LRHh
5j0QdJYUWlBMQXEPOBmEp2qkAqLcAd22Fl4cqVKgD/3HysJ1QEnqYrIX3HPWoBcUnExb+3OdAKoB
Kk7Ho4queGhboDT0e/AQKHjbWSwcK3HjjRxqql0rkYhjZKf3mEy6VyL50Q9dO0uLhLANEFT67687
N6273gRTcdzVAOQSFLPf/4X+wfCS2K9E/EGoXiBFpbxV3axdJArWR01sET0kIQljIgsGY2RDAu8D
eKU/BDJhk5WIBNOdZjwULF4J5ntAU/GKx8xCtMdsLsAUsNzEBiMDqt8iR6xr7K+h5AIrKNYZ8YU4
Yj7khBFWyeagiu/Zxk9CVRdzFgxw7ywcagHQHgLVuBus+BYktq7uLZg6HBAfsUff+3PMeBAIHjJE
zZqTdHU30H2GYliO+3ElPJYEy5DbUEF16iGNy8oupx77YbIKBdAjJEEvXO4tExDuDM0HQpnih8iB
d9eH+p1vhFQs2l4JS40iXxA6sIrjILp8+1Z41Ufn3gmE7fCqHy7f4tvbHpD/zF/MuuPB7LR5UWnM
sBygMa0IlY7wltMDbOjLSiDu0NiLQKYwNPyiOCT8grj1IhfVtMwmbFJPoR/wJGKaUls8OJZgK7Bg
XJrkNVQs6T5rkmwnSI9WSQzCDXhE6jrsjBTdzHL9SNiyWy3kN4asDD1hSoCxB4ezvyMvAwjxdEXl
XDLU8VgQNOwj40ilkQ+9Ua3IqeKqIpZEQIS2CIAQaHStYVcZuIinLKMC3ZpDp7LqOyQ9dD1osyEb
MyBXoAjs6nzDFB0BuJI1aW6Ghh++OIBo3wOS4rbNQhFJysNuAq3dQ3d4lIQkgxjQ21wgPgDp4reE
k2m+dB4AFqzhRLBD1SQI4TdQuWwPZJxAWVuB2UQ74RJyseXbZD0HbAM7SWWM9gsIg3tgoCrmg0Vu
E33qQRatneiIkcxhSjYByR4BGtaAtQgVLKHlUcwxbZ14wDkIQnWPiWRgPMBcof8EkjMWgAIYDpG6
l3YNsSq7010ghyIIcuIRc+I/o28SUilboAYgKiyUZYcwAphn1kCM0BgqapSXVBNyq1Q+xKsfXH8O
iI38RcxkMiOdhDJpLZZ8vomhQ2wsu1Kjxp0Ip1dyOozp0aGOEbIZqgul21RSRHhZOEAuIKZAOHtU
1QJkhG5RTj8MJiGiXfowDh9ZA3EG7Sypk1JZXrKTemNKwoLkcgzChtv/lw8AHTfd/SaSI7Y9BAvB
J+GPlB9hnRaJP1VpSt11oARgbBtnlCAqQH1C0jUJTd8DcQH8AH1EXtw1BNl1sBZckqfIWRJsSuoN
6wBaz/hGMj+2MECGRX1C4NVtYORVyfU24DoQFqqdiFCCfZWTIcumAwB5K4IoG2azpsYZvSntkBp1
U456KT3ICpivyu1Aei7FKk0ddkWVYaoMcMqaewkpOLMXoPzB3YneHGkOLFCNIhspxRYLzYnrjByr
bCC1C71FIP3JmdIdcYBfHz2WdR1phAXUcxjgKdjTNEb2ww1R3ZYkIlqRpdNBLUJ/rQUallX5FVMG
GHMKg1BTVySFEvoxyqFRaq0S7z6S+O4Rs6H4oUTsGUYycDRM2pVHxAohqPtIAlVQ46LlkNWFVelp
Vnxycar6ee3LYsXpQ5GLdoksZtYgW1Fgf8CYSexXLLCPhRy1ogXdEGakunJvVVPPEzHORWooAWm4
Uu/MeQwGOKp9jjYlqBugJyW+iAGlGahypdSai1QDgQmhNY2iWJ2DjB9uYqz7iFXqBjGjpqFmK7Hu
CoiVk1MpVTLNRjY1qhVbijo1gbIsJKo+VdlHcBQAve/B8gTCbQ/vwPvGHsxB/jw6drySEpL4O62+
QtVfsjOlhjMFHRFiDNAqa9nATyvuLt6CSS1tBlsAnamGoElJf75nMmSqC426DKuk84TMh0YHd48k
Y2PDyiGtMiAbQaSNmvVu6A21Xs4sZDQ5sNAjuDhTNI+9oKJeTQsIPB0xT5aXSsX/jdVRtcvJjNCG
o2xtv0Ukx1ZC23VTNRWXrI5Vac8nZ3sLbYhhb6B/0usgUEU0OAiaRgtQExPdqCIVWeSSrSFrqWxy
6CaSL9o6HhASkB6JGp6rH+QhejWx0TygKN7uDXEeTcgPt4NJ55KRLIX/rAQcFA8cFKrIwUAdTgh1
T7Wcdi+duFZuDiywxUE+qLESbZCigZ4gLcRID42aUgwooKS+QeJARxDTlZJRvJxP1pJJ2pNjZEIc
4JxHwmjssA7kX9LKEWtARr0sQ8RW9Q2xYiTMXtRpRrFmdE9UKIBhyFW2hwpdziQ5gpmHiOxNngTa
H8jk3H3km0jWreoxSDInlYmMWms/8UyxHimrR3cCu4+1odkNEhcfL9nx7qI8hFRb9l3WkdclrH7R
KC1N1OUJ6YvNhaxtLjD0zCjqgHIIpyGtVcYiDIEm5dkY3HwgWnDnHHQ5BbowwUa510rDpGYKsf+C
YyxfCzslnBaJS2B+BKRaiWIkPqkgyI0J0acFwoBqNap+9dGbkLwR8TXSypokIKqNdPyFyUCE6sno
8yfGi3gBP8IiqZ/RQ34uiEhH4KInkVFMzQNXvSMmlUUV3SE82CAoaTDoU0kCG2gx6yC4q4LLRijk
lOk22fHMOdJ9r253Xkm1R+6Qnws+bSLU/KryxPaUXolgsi7Z+XfVFvhB4qra1DMqnELFU494sgLY
w07L0FaF6ChCTCIq1yCBYwxbqNS6Eg8YPbpk0mTTUwoY8pIATBhpx0mCJOEhzQdVF9RyhqVUg1jp
Cb4+cmwoTaQ0vp47QPkSBONyDsgKKfI7TxyFpXxBHQLIUDHfS6YeKAt6irHnS/YLPlZAQoCFCwn/
wBolCV9qa4f6iTE1HD/yNUsjcpfspteaKGVjxqVIuWhbTxrcugxZ0mVhLnJMSFZFpBdwAtegLhwY
kRLkxhhpiGn/fsh18IdiDy8b786OTi6e6kfNp+ZR4139nQ3yVtLmYQzem4V09P68xpYhjyL5dnzy
hsKA4ikWHmIuwhB6G6SNGYaeW6B0VmYKBoc8m4e5NH89s/0YLL5cqlqPzBKS0DXfkd/M94XjAj2Y
Kct1Lii+4lGuLw6qSzPh14jC/+l7YOWHAxIvJohatV5tQAKINRyMnQOay/iYmZat+ZipEcVEo3wS
yJW1mTIe9nK1b6LfXIrtqyeWZsX+vfCAVXMoeHpSo8Yu1yFhwyla26g2qk1cKHACuZhxUcU10G9y
ZSItDq9P6zzWfexeo1Zr1uuNC0gYXg9yOLP9GXWtmAhJTn7CgLa9KMoBjsme+drPjbnQA3hFU7Uw
zrX7GDqF+Q+UX0krIQ0a/nBVoD0UjUnsuFGDkNQkNDjLuePxcANJTSyIKyzEZPZcQeG6jRVugthX
CQ2JLbDiXEmXNdUihtpw4SxHmPbWnDo5MiBcNc2kUAD9I6MtE0lwOKHYi58xLDsYkkjNCvyT1nxU
u+rpEFh2+HHIPktZx97/TREPyrXxBkTtGtO+exlq6l1R/jWad1BRn29Y/QxXfpqsfnxZu7hsnGiY
rLm+Y4U+haV0hSre26jVL7AubqF5G7JfsAvV+tnZaRMkMbpdgNkQq/jsRBj1bP/1r1Ro6rVCC9d6
rDgJqSdP2Lm2WpkAf8tfr1GeQo4VWaETxOyt57v+0mdvxeWvKkmvZIjqrxFj04NK5dGJV5V18J7i
gwdZEnhKC+fpfbYkUgGMV4CEFJCK85LLUkEfUKVr9xjkeiHFWjr5spZbSPgWR/kE4LF8ghS+hWqU
+C2kZkzwPgIGwSh7Lt9fV6SALqSjiM4naWovrUdK6Hwaiqd8ima+0ipQROdTtLwtpJKozqf5ATFJ
aWLlV6cwuGBVRFOeBUu7p0R6PjEVzPnkVI5tJUtJVkh+2sYUCO9CAkggkzDn3woTSqlSbpVlgIY1
30HWm69Lu6QM6FjzlXSqmaDEZknJTFqWZwIizBQpJUtAlSI0k5RmyfEo6HJjkmWa0g8llUakiApd
kNo5lyIFdUkFT8TtOzPMAEsuN98iautcj21fjreYKDtipPpJXMHByU0cIN+lUMWlLBB7WgL2cMtH
F8XrAsTs1PvshDGK0msnpMDvho2TgEI2UEgFrjNJKtd4bzBOfggSr+p4zhs2BKGD0Gzq9cBQBcer
BBy78Pt2d6F0nUKj9AdbhiHi+i4tH9lOSJ4pt20HG4URIQgty0bY+KHnewLUYasUIOAhOowGHKpN
hTpQZ7XaBUbXMbGj7d98FinlXN7xzkypEAEEGkihjibjo8/j+mmxFRN4G/aagmIpjOdPvYlc9xnz
hYg3uVlUOWpYWvnK1Ej1cuwsETcfce0WXQ4AVCrKVhB9GQfoc48vpTZOG5D56KRgdNakJPBrHhwk
jfmGpfLb6w4fTkvp7XqCG3vMrKwTU09vJoTqEFdjcFn4mmYZKOOIpvSIlsaOGLgM/IgWyCEd/4AE
zdYmqyg+ZXZE+fAXtQBAkMSs0iYXsz3ZFhuT1GcTXA/HHlLjsQVVJzb8AUl0xGI3oj8PYLXph7p+
aOiHZln1N6Q2qVIV4KuSmK3+5UitxVdDP64307fYB0zhgkL6Dn4jvuvif6HHKFkLG5AiSP8DMmD4
1b8gSinWCJMEDt+arfk98AQGQ1UMSFIGGUlIEz29AaHjLUGcXGoCpzf2IPcgHYEUCDYhhkrYofVG
1jGBlsnuon0cDP6h5GKmRcsezsvKHyHllNRByxCzP+afrC0nvDBBmVXwdNXuo6yLSigWaJYkqPNA
sq6HmyLYZ1qMJ8OYAmb0riusRrRvAnJr9IciRdpaw36o5x3NGSZc4XVXgdTpptoH/VK460JGxnfV
W6D43zt06ESVghozGx4xf7BYqB+VC6Z2qDhiZmEsBwWhrrxOf0og0TAFan62RrWBowwOt8XMAqRr
kqRqK4XxLMEkDmcPmU+1G1b1arZQKrAcEmkupN+dztrLMSyxC3bdbIFGEY1Q/TUz1RarIh54uJxF
ArcEAs5AQQYJzfV/0J9iNlgcxXxA9Qz3SXn2M2MmSLl9IZqBlVboJ+aCiH5BRfMQlJjFg90Qap1l
Zq1Qy1NLSbyonOPD3eSmcp6BrJ21wDkjcS6e4rereO3mXnBDHnHEzMLNvNK42NGuAtS7Z/eDYth5
RlvzCW48uR7cTbKnDCaKOZhsgQGb4c32rVno+/GelnwwixczGM6zMPsrkuw/s918D1Ry4EfxDJXv
DI0LZUgYUNh3TShSZ+1piYBB4D8HognmZRXKzVAKkERwBQSLeIKuQ/9XQaHH2iCboamJ4k9iEH6m
HlLoLAnIlM0Xw32dM1zW8CWjNOgPpINeo2WEKu6JwpUbSP/vCx8eonjjivfTAwt0XHjJfri5OccY
+sHf1NN/f4tgf3t1AbNRvfS4sw7cuXx1hXXIp2cb3VHAbFTz0u4KZK/l04taLClgtngvNrirdV8d
Z2e6Dnx6QaOlBcxGM+orr+L6WvdbPj3b5o4C0CYg1BQDhhwHKx5UCtI4LWS/ECryk9ASO6DAHgSW
nSvtnwMAz9mxnHi2cJNolWcApWdAr0onsfquJGg2pY21e3OxJlA2MwF61d7L3Q46t6DpXgAKMmUH
ZrKc2Zo/zVypSOu1xrH+xV3ojlsFh3P2NFtRWKdYCQHQvleUtyGfZVvtd/eJCu0VdtghefIExREK
F9OIxNyiPGrU5F+ZKxHpCdpKO5M7WCD79Fj+NYF05ZW6lo9Z3gOXw6gDSepfmS+XqUBLzea+vcFR
SwfJqIV8yJncj5jmIFr7Uw/Nlhmu+CtJW44FaXzM5sliIUJTitfSvOcJQAHKncp7GiN1hkPDlVGy
zPryL2SBYeZog60uyQNwCGrPRZqfkVOTljuuXZx+Sh+2wOKYpqIuJ6yOM5ZarmB7WfjnIc9gUo3N
AKOu4PdRaSYeDpnJ/TMFEg3Fb4nA/eGhvW/8uNKPhDmjDS7Pg2lu3wWmdhrMcsjLyCPCU1EzooOY
F0yHcX8yxGfadr6Cecm9QNl1HMy0j9I4kX8heRPNYrEOZnuJCqCA9aoLbjmuI6MnvcGH2d24MzKf
M0By1GUdFSsOXeMxBXJspd+VUYExLC8xsIB7dObcuidLcXfnJEPPNINrkmr05d8UIH5ulCTJn4dw
PKeaI8umZPQm8nkKgV3BYyckvjGVwmrmy9QDUeGgWRhldNb5MGyP04ep96h2lOEy/cyC2X/koaft
RoNgMYYeWFI2z9QWb4PzzewtoY5sUEWjPUzN8YzmKFNuH5/hHnVfOUcp4RGAMm+XVlnekyUCkslK
YwKzlvchg5TGglQMOU1zIv+qAus0plZWnVy+eoG4A6eU4lrkctJTebRXZhmOKK13Tr0BcOR43GM9
Zx7ycGNC6Kw6rjpHDBz1W/8B46NGsY9SS76wFHSWVpv0A8v5UWZgAxcx8Pdu1CsNUFAGHhPFPXKq
5bPq2WkVpr0l3X3wAW/ABkpCjCnRLsvV9S3R50+Y0gY7vu17JHpvfR12VS8fxuPKrVj6saOWQTGx
e32blqYwp365D+fHGqgHFCK0e0u5rjP/lr7cTnr93MuXK11yPLztfBikmYjD7FnGd+ll0htXxqOh
LvZxMhk20kzouIoFY96nzuiqMxqMT9L8u9vu19l40P7UmWSoGMqmdG3j2XA0+PpTmt2/6026s3EG
dDUaTHppI0N1sDKSsSUr1uHahYrQRkds6QcrjF3K30iHb1WU1lnzQP6FF9fGF/wLL+vfYqgu8IOm
/AtJYHhgOBYDsxG1EK3n9CfCvzKBao2F6wkoHQMUDEyplafz09npcSWwKiCemg2J523yfSvJd+r9
DIxh5tdxR0CDZnU8/mjmQEoUrRpQ8qJae2UIDcgd5LI8Er2b03GzjP59S3ZcGWtgBobNjGgWLjJU
a00oezBw5eIrns/9hruKcXGednV+zsE3qqdAaltAkKmNcWQZtflVg+GSBp4Ftfjb9gr+Lv3X4QEH
ph3ZGW5fi1U8q1kH3j49Mx6LwL63zKBPqo1ms2k8Kugo8UInEmg8OdKauahVz5tNBZy+ZOCRiF8K
vQcLWxPprwkxg/7br/1ePlir0pCLczMi9+oQ4YFGzOUBwdVryLtQrkz4f6XlvPIcn6azNHMMdsKa
l2aNhMufbj+U5snYCdKy+VxKqjCWNV86pHlPmhcKHpfN4alLkUqgDMeWIh7XOuUyitKI3xWulg2Y
4RKYZb4Al5k/5t+KsOAL82W0j0GX1JcP16V4gWRj0uYJ+ic2O2zgFiBavoJRAuQbUFuhEBNUj2XV
pJk9x7tXkW1accEzWlK7piBFIoFOdG/YiNYSy3oImW3aJl+a/eOwUz7jMI2UZzR3YYwIVMTtzoKY
lROvp9Um+FpfrvrDHRTb31XV12BtVtWs0eG5r1flBXY1MPnQ2o2h1xDa0q7+GoilthwN41eveADM
OlA/pfzRH3ZHphxvVmtStdA2EvVbWvIjZGBrcgGPiHZtN+D/Y/j/hEUrXsc/jcYx/Zyc4k/znN4A
bW9VBj3KTHgkmIrKggdVqqLKNSsIA3arWNv1xrl+Oq2pJ4SXT01whh9XTugGvu+C+liKEAocNdXj
aS19vGikjwBwnAEcZwDQuCcWYaJ+sJklanv8o/bJMI7BgGaDWaGl/87lj8UW3kMdEvGHq9/TY/kK
v7/6nMdsxYHJZR/lI/VRPlIf6RFQkz6enKYA1PO02HFW7DgrdpwVO86KnWTFTrJiJ1mxk6zYCUOK
kHt39EMpbcic9NBJaj/jZSFztfdHQ7nKLXgwWbR++jpOkAvdLw72KegXh/xkgRcHiDD6KTenmc/l
mNKZOR7EvaRGXmvYTrKTFiFrXXX1vo2scnW2zGjEe6VtpOuqkmAFj1af4C+4j1OPttep3x2ru2pD
l/FYrp9VXrpSYiKCdtBmMKWU0mhSE+kmsfzbLptAZ5cT37mqBHdZySe0l4yqOCE0zVGbTO0yk0mB
qD1OOXvrwsiPsu0oBhKzTS8gqct2yGRyPM1VKwlC7quQXsN6vnCl58Xk6mxKw/pyBtWpbOFelcpj
hvz5rFvGrOV2f0wP5HDokoN77v3qqOsqZOBL3ndAW0xw++IRCmprxWhDFlY8T/A2Bbw0LKSNJB9u
71gPD+eETF4N5rJhMnfBqOs5FrQv0k6ipfM6mtdD0UGcZ0KaKbhG4KyAwFwkXwOjEzpLl8WfqZmA
s0Xyl0PPEKfpYjSR0v88pCXo/8UDXGuhTr59ogXp6V+BuN+8BMZo7BUSMy2T3juC2SKJcfayRwMQ
f2AC5Dzsw2aUwBN4YrGgxXngxX0zBgXlHt/0qVQmqCwYIbQROZYywmM6pUtlaV8pMSI+dctjYC6e
KiLPqkSy5I9iTL2WJNEhQgBNQkE0uCMVlOx6fG++Km0mvYrwaTxqWw1FwoFCdVQph3cTMMj6kgtl
KiDtxugI+w7ayANrLDabtVP9uw30+OL65ObqF4NjwPlZYAqyakzfebQEJbd+pi852DyenikQ4rlV
Dy8fKEd96KtIv+/JFR97FmBntvWy3uOcPebI8/NuWjSPp0O2YhGKg+LRUBWaM5JJ9KNK287Su4bl
KhszV7HQr+dbOc3G2em5yjK2PZyf0lnBtrqfAMQNnQ8F5pfsKYOsWa46a5oHwvgh7gvV0uotTzcc
6/uAMnQc0XLXjC6IO+JJvJpJGHlUaYZXBz7gqrS896oEgk5zlgPgzKHCQGeoHEK6SWkesDjIkXRP
r9yqqo9NHWXySO9i97KYeZmE+y8Nww9kn9LT6vKQjN7PPVRbRnGPdzSdIr2oHd/whqFRNaSq5S1e
J9XSgnz//q8Mbv+i49TDAwG0ya496rBDkMUumXsy7gBu/DJxeQizpLknelOqGah4CerrYOOeUPS0
Ujup1C4U5J1aSzIhlWtO+T92J7ubwcwJLhLocDQ7PZ47MTt0nTiGTuMBbO6xv4KJBQ7F0hN4Fc5r
sIw4qaJEQka5zxbk63JPjfGoYNVWPR2VoLT0mEyxfPZEeL8eqJ9SqsZ0O3Qe1O4IyRtMHXPA6dMM
oyu5JmDa9t/fjP/e26W/9+htWWvWRqFaqBQywIt7ysc6ZbKmAfLzmk0ZbMHjhvr3kran09G0h3L/
BaGKfSQmlFkV2gVBW9IZl9Xk/YrJC2B+7g6fhVl+c4LcjV1m5hwyG8Vc7V6wQ5C7Md7CgKbn/Bve
rrVPdmncMNklH0/m8/AtIGqmEHXE/NABIQpEC7IGF0px6/c1fxAbNl6BNLivqioWCd5tgVso6NYC
gPoQiiUqjivBH5R70ocBJxG78gWwUYhFfbX8i5vboZZCbCO/ax1D6RU8dIFrIOwT0tQ3uh3mFSwG
XVXr6HgtwJ5NJgiI2yXpmpWcUaayfkug1RnF8XLZABDrUxw524AOwU5pI4h5km07pXzLNypyfY45
/1aY0/QUb+6llADUQkE5bejTdFiLfNwRWVUHs9KnXdEBlSv3Z0V5NqtReCADKo0g1FQMYTzsqZ/S
ptITVTLEAh5N2I3lmfsjUC2E6geRJY2FuMeiRkrgDubyFgB6GSfzXwHXU3lpsKy3RRtmszKtMOSb
wuuAih2xK27fqAVzvLy7o7ccUE6f7jYspLelWZPV11b7UuQ6SpaenhUzknw8pGVU1lkHsZFPFgGd
AM6l5arFG/eyty6YGR6IWTPlAdd3WuEyQXY1GtMwGWxPeMt4ZYDQbVxGvr90LCO7r25WyCBu/ZHA
TSlZCszqYHGFt4RERklKHeH1OmYizOICvCwjacjxEh+DKApFUiIpTGqavjU9Rk75PKUAJROW5u0s
tI3UNAtsJfFUkj4JhTCT81AJrTYbQwYqv/aTubtBz1fYeFEpJSKx4HaN9EXTNL0+CZtQRK9gywb0
0He87Jk/pc+y6Bh6wJeCUoah4+MNxH/Hq04oJXsax4BGepqIdWA2fYcxrMKU3uFuccgVNon6NIfE
kjwnSjKDzIVmuTTcY0q8XMWoxtARRg/jobBzSWdv7WHfZSnrWy6oFxuPrylAJ7s43iX9UGGP1QbA
FMq4LOy718bkjq0qT6GNcyIya45NFk+yyCy9t27PSRQJmO7JKm3B3I2WP6Wioo146nYm70PairLn
wxnmcYDTmvw79Z7bWCkveaMQ5SxybIrLRK8pEKvlaP4eLIXFEUgj9bTAPcnvo9A6wg1S718Ck9++
iFESG3C30qGBLESAJ41CIU+3V5/pcg5W9zbtkm6XNqEvVTRmF/1m5+/xaKN+2WFKqKWBr/n9EHpd
AJPxfv4oKBxINRYOoIZG2YKB3I4oT/zLFkbpPvF8B9T5fwn0hV6KQE96GVc+lUoTlVViyNSq51Ko
0Ply+AV2/qm1YwtI38er+fMjauBJVV0otzOwUT15HT9jF6p445AtZmrJy9jBaeaqDbNlWchEIKbW
2wA6hM49H68adncBgFRSZKQP5Zi58k5GDF3V5F8co3lOVQZpyLVXmplCggE5HeprHQgBHVXXeNNu
11Twf+xTOZFLpaPyafJ1aohjHCCXMJaHwEjEfIJXunRAh83wYnlXbvWgXWuywpUjua9x3EjT1o42
LU8wkW56VpXQPvaTWvMca7gxrvTFjPrFWb15jhz+BafWLFTT6kAeZyZ5WKj3vNZsYK1bcIVmTo7P
z86ap6qz4KPQPtesuyr5XmxUGhAiXgmnE+qnDdwENRj08T7tWB9DqMkdDxKskNGna2+Lqa+LWxF5
VOcuaB10+GbmDuldMSxZRnqJjv2H35YgnsS/ok6j5+BQU5Tc2szoIuModx5DQdlJEAE6nooKUudL
CZRXsvm8meU6e/Pp6Et61dqudp4/UahBqT5Lc+RLYWfl+NjutVFkYVgqewHT8EDJyNTJH9xjOMs+
h1E2F/JckiJ00yapS4lXPzeAHcWpeh+BOnZDzKy2T2tQFSDcjykAAtEfScNJhQyLHSSYlInwMKqM
5kvOln93QeMnFDLoki6qAaTncuoNeaIHf/OA6bGZsv6toFP60Ea9caZ+tmFc3w/yZ6yKEKGIk9Db
1VuEoDGJJ4msMiB5LszB1ePE04fMzusXDf27DY79miUeLktF+6oNfHcDUjlYORadVolMtVkEDrU7
+BpQOf79wCkJRNuH8YrAGQVEal7VTx4Uv4wwS29ElQZNrXaSPmTQeCJQXh4AvmN2ak4HwjUYts0t
S7jyrs5ZegFNPRcQzxcgrtWkWKQzBHgkLYtrkXg1mlqDp14aPVSH6uQ9H6krUzby9ZoHM71Fez+n
+oFigWzIxQ76ho1jQD2d3dx0rm5ubvJvWTm8RA0kMYxL9Ty1W/Z3CcrRRdYvACQBOMssijKRiWu2
oa23XEa7wdS2Bh44zzcdige5Fxnkeih+K0ObAaJXrsraxRtJZ+qQ+A4lAk7RzHq0yzOzRvCTaWn8
vqypFDQ1rqNinBkvIEND2Anyawzwnl/CuECvAPyFb8WcMwxIX/3cHW4tKdAi8NefS5N/Hk+uixm4
HtzqjCtI4UKebDKLUBYIvx1ZuPOzJAuGiFeqeeowR+lWd3lJz5cQ7y8I5SU9xn1Cl2/fpjA36flA
umrH8Wivmrp4J93mVrbpTB8dkaGxspzXGKXUXrq3KIfF3GmycrCMqY3jcgbos8dnc9duSe+SUK0c
TfSv8bXjPTghfiDMoytqPqtTg3Tho6yo1evh+cvxcDS46fY6hVVoPHiCS+3D69akVW7vtoKAoKYj
n6/JQ+NRetz6mo5Ekxx7L29+kuvZqvobLcqfW/guKXb4dH76prQso6y9NXw5PW42XtbwoD+8m3RG
t60+ISe7zpOqxO+P6Hq+dG+vB1/G06kMy4M/NrXWtrTq5RIoIiqFljG86XScQkugSD9I5Hdu2rN6
/fT8eFZvnDbO6henSv3ksk4uGhf1Zq15upXVaJxDeqNRK8k6OztpXDRPzutbWc2zc/x83MVxTWXd
DMezqxEMrzOaAT3MFL3MxpNR9/YDAinfM8b1ftcPMfhiFkIqKyl1rb/k9HHQ71yPup81CVLCsDX5
SHuj80TndW8nnd7suvN5Nupcd8eTl9PBFLvpAtalfy9jsHjv1RQkw6Dd6r2M2Ek2YIkPg1sY2Gd5
mhkqmZoE0u+2Z73rWa97NWqNfprp0fzenlrq3tbpFAXrdO1YU+/2rn8FCB7cII7bnfF4MBpri/72
8+ebr7P+4Bpx1h3toPvbz93rbou1wShVN1enaZ/B9PNZh74/A5BkVcAsDDxBlFqOK52bwbXlfWnh
s/Bj4za92e1k6ukLEX8v5uAVnJnpFL0vF5yGFJXvShCS3qo7nf5q31fqZ9Va9aJ6XgHXIQr8mLz3
snId8KgD/LSIjXZcspbFcYNE86JRVj4VBVpwmKnvdgiLL3Ox3pknk4Z4Y914JVzABd6ZN53uKiD3
F3xUAKUYLiOP4WoTfdXIL0OFuh1tT7V/TxzrHg86wuNEdqgMHF6TyeQnldXy7NB37Ok0AHWPcexK
7Ptu9O7d68garA14frjudcejd6US3EzNQ5RNREne/onYLpCfiL3CRw8UcbOJVzQf9NusN6FKGdlT
FS0W60Asf2+dLyhv8IwaO0BEJQWrmjTkzGWdlGwBLA/CsvOVJHsVlPC7audr5131qjV5V233r99V
P1+N8Q+k/TjG/+Hhy/gG/3x8V+2P23T126gtT9bgiRrcEHPVvQVBTAcAtyNvQzqX3e/edmbaFNr6
/nX2Dc4qXTqRCttZa9T+2J102pO7ERVV13lnAN3rzu2ke9OVqoKy2Q2YTO4GL9Xok6d2es7GsQgC
jH3Xj1griVcCPxgB0GZVvc7nTk/fw5Eljzqfu+PugI7JHx/X6lPPMONKLbvn7bDX2VwvsK+wv/0h
zeufhn/6gMffpdG6U8aXspGyed/tMLx2Ml5qKw/vrnrddkEVyaMT4GwAQgGR2uhr608iSUY1lZ5K
Gqmb3czueJNOf/giO2KKa+MA/zpwtKiuB/1W97ZomGY5s9GgBRT9wTDvi4B6kMq0wqSCM5C3vXAL
hxNuDfbLuAUGTrvfup2h5bZrJsctNuRWn3vp5Yz6JpMdDsqfZtK++uXPBVflz/8oJWkDXlpyGdxz
jktWdNvd2Gqt3F3YVwWxyI56yn2WHbURd72+Q4YnIwublJBrCr2arP59fk1WLPNZjJIv9HGyWsq8
HVlffQdY6vnsBcu8oP1gqUe0FyzzjkrA9ntKskCJr1ReQYnXJGtI/aasXOpBpRNQyESVKvOKPJ3B
FT2r19DrPt8qa8H0sp7lTeVnmaVTj0sPJe9zZaAl3tcfM5oy/ytrtswTU2RymoPLe2U7+fn1flnW
hvapduE587m2y2hv7VVl1UhN3y3LRQ3/x8zAv/24f/tx//bj/p/w4wz2lx6dlADf6dMZtaF3p1QA
+Xe5LOXpyfwSX88Aznt9ssSzfp9RvtQDlNUoH7AMOPMGDdDX+YNl1ZJnKGtE37AMRHuJEkr6iQZc
Zks/a2C/xD7eAf4CW3i75F67Nz9W8DAloPQxjTzD29ypcv8V/qbRBfI8t9Sq9j0zQMMLVdDaDzVg
Mo+0zOzLvNNte94AQ0/1hbaYcj6Nst9fNPNT9zkkO73Z5wpliNsycw0vd0fnDWDp8e5FYMH73U1Z
hv+bF1jjTu/m1cJn3B51h5NZNtDXl0UUfFd5FOezyah1O+61Jp3rV5e/HrTv+iAEYVIHilnN7FHn
73ed8WQ26fZBMvcGLQVTPztpnp7Xmscn1ZPjs8auIkVgEw6v/FVSF489TL1D+eWUX2ovGwOdCM1V
Zxl+YOf288tjFRL49YEKKvc7ohQ7yn9PiGK7qtfFJ2T5Z4ITupHXRCaozO8LS1AVz8QkijBlAYkC
TGk0oghTFooowJTGIQjmu4MQW6VfEoGgQqXhhzRnX+yBgP51gQeq/vuiDqrosyEHgvsvjjdQm88F
GyTQvzDSQA28JsyQK/CaGIMsWBpgoKx/Rxf+HV34d3Th/7voguT9PyS0IKvajivo9OeDChLyOyMK
svBLwgkFyD8kllCocyuQUMgvjyJIoBeEEEzA5+IHW7AvCx6YxZ6LHOjBbYUNZMb/uZiBbP+5gAFB
7YsWSIDyUIGRtzNOQDDfEySQBb+z3P7wQAHkBbGBtERJYCDNezYqQJB7QgKU/z3xgD/6w5u4ut5G
W0Ze/4GvH0I/CejbpMAp7Sr4v178TeDFAbGzZFf8/p5eVtzDQ5MhfxA+SAoYKvuQxGvuRXjLQrRO
ItYToe2HCwCGwYySOV4ewCNrxdnYWiUACvX8LMQDGychj+6dI/ajs0azDeiM21RpKBz289oRD5BN
B2j1bYjXInKWHvsPpGA8Qj719nch307+ehpC6v5/dKUQSEP8vsn+f/QpU3kJp9rrrcrpT/3u+qAr
gebGkO/zOOaeE7n8AXrvbqKVeCiO44hdr50YbwuI/aUP2V8dzwIBzj4mUP7WuXdizoZ+4D9MvexT
x2o7uPomxb4ebM0HfqpCfQaZLv3BmsA+zg7e5kmmOPc/woDYBOv2MH+I3+hin/x7sGg9fX2BcRSg
QHL5vn0R39hNEuJHBqAmB0+4VFounqn80d8I7DuPfZddgUuC4J+4C2Me4wGPEDADqcLLfbz7ED/S
8Ya18NJMLo/z9fhG7kvN42hPt/SJhKi8nlyfx1AB+wCyeO0rRqQdWfImjGhHoeL8g/IO6QPSH5Pl
SkDnPggfchDnrh9FHl/iVz+6rsNZy42w43F0v5l6A3ld6sfsSEEeu9vCoNgymGsrDhbEF0CshyzV
1mcxYzx/h9enGWfnWx6aght2A/ME4y5Mzwv4kT6honTg9zNkK6Ajpo1qzRx6lwPHgCkJ0ws0muDp
BNYJhXcfchg8O0zv0DKKqyMneDAdDIv2hy57C8ZVFOMTVLklEPeI0hwPQ13yMy4dG3rxidswDh45
1vYE/OhDNXiPPM51gqwEMH7obPxo5QBXOd+StZMTCSAE1nN5p2ah9qmn+w6qyBJRZH53XEmBW2e5
5nEC1HbEbCRyi8fHOJExTuy1/7DkLvRKhP5asB7wYIy3NsQiCoRsU5HmF47RSjBv7TkdB7kR4PPi
pa0ex0EhQAwCAmj5yp8D9Tselxd07p91LdVeIrPTIzEmbVy1WV/tNjT5HTLoYjYSbjlmM74dvS2s
2j5Ass+OmANC74+A3MJ4jRznu99A14uFyIkw+aVolKn0/ec82+svM0HqdjXqu0tl3bvGb9Kgg2wK
1Wv8Cso9G4l4RaO7vqr0ulfssD/Ge/iAODdI7m+2JM8NMMM961fZJ5hgkuYtG7T8FX6k+BtWQ6cj
tkR+UfGCXUZWzyrEG0eB8YDswefBi4tgtkcoVEI72i4ngIq5vEeiRNhvC7jO1+5NGSMW6725IW4r
8GD6hRSUDoW6tbZhZgfGlh/HULn12bHww/Z5LG+JuxsnFHMntNVNjHR/D16KSKsPNrsC4bsSyYNw
AVR+hw8mdwHY6uA9OUoxP7LxPZf1fbjGTzUt1e0Ye4VP3uL60U9AJbdWsX+0c6A5TG+pAR7e4yVb
NqgB6IeIJ+qLvS1XPLGhC646IAJybu/Yh/7Q1Anb9s3U61rq81+jxGEfndC/54+8MIItIQfF+i3C
0gja7PlL7qmO9ZPI96DXVyGSGkoetAR+rWjl1aMUEmEOmNxrVHoDl25HLCIxj3Jg8FUCE/wRL8mZ
J9YKphxGA1WO0NQAQwaJUH4uJzudWKyzSCUvomx1C5Q85mfeeQJ0A/I5dqCizy63nbUTsq4f2txD
01BReI/fr+JNcl9uXn7GYsDED8C/APLJCWOHfRYusD7et/njWO4j/5HfJ3OwGED63cPsDNYgAj85
AOUUOQEM+Gs5NS1on29YN+Lcgh52YOQwIaF3X4LrD3ivRAxGiL+OfO2IfAYFwUFggbRSH2h6pRAp
2Iw5gZ37WoC8qv/G/A7eJEruuc3BeL1PNvwoR554wTnei7rNy6XGWK4T2zy3rdZV/XQc+md+j7dv
giRUph6NNk5lwoZ9RJzghN+5C2jLs1GIUAXybuvdYFs15royTWq1hUXdGbS751vG/rbFCC2BROVA
kUjb1/zBAQoFH4QuAuRPQGhAeGrUoNc4OBUjoL8tkyJvfefQJymAPmAHvfXQAB6A1Y23+xhBW29w
Dcp9e3pyKpZgioMiZPEIWDrkvwIukLe2FaHm/KrB+oMgvc3ktT7ebp8uu/NVd1QyRZGypRL+JPDy
4nBbOXVcx4+B25A9FboOYU7fPIeiwPLkF0p/5PgZE6BDgcIVJpwnNtTHrkAEgC1ZcuezeJKH3Lc8
SvPqXuSY3M2y2+p6y036VzlI2JC+Adb01EpiHTnNXHCLtuXh0I/kzTyftPD65IsVUHwQUGa8DEW5
NNnyCEp6nZXHaTKUe57sfuJR4rPBasmlKoOugAD3llGltwGOh4rAandprlGVQF+TwPHkhfOuCl0U
Gb54b21xJsAQXQPzgEUsdsxCgTjKZeFY3Rpeam1ukZdax+vLqymAe6RIkKWB7TA8Ali8R0bbRmd2
xe62eb1NaqbugbK38uBOkVxA0gEO4Ocb3nt6j2K379wL4CnrXik78SAwaPAIgsYSGgvosJIp4+Nk
9Tag8Vb3OCfjgVSwVyFMVI8v8FYa7jzrZuqLf7UeBd2P30BEnV7CNUrEXYkE8ZNEZEkaUgDro9t9
0aEjAXktQLDJm3xLiKETOwKGwz55Iomi9IJOvAL8GSGkr/nEGSnItW1lSji5Fo/IeDKazT4DMUQR
RuGkW98dtrfb0KBjseYBuIfyINzER5W1MfNz5JUzSdp4c1yEn/60N5IZV3jr9XIJpj3IhjJyS+9T
LJGU5cyQkuZeRbzlGOauSMyTbe5ixLw1tWWdAvT4JYZYepFJiX07EmuH0ScpYgDDb6SWOjAkYkcg
KMFsXG0FkWEo7NaxQELHsVMSmtofOyCd4ltJdjn53tCBjjAgVYsVqPaWtfITvGgZ+NpeCRecYhF/
2zJjbhPPB+ckQHb6KGeyz5cekD/dW7xyXEASfQp2yxC7Rs8EkCuWCVqIZH1/Bi7jygkHmfIg0Om1
ndinmZOh1bb/OE9Cj24cDNmtDxzWB9SjeFD3Vim+HlaBVfxHST34cdSPwgud3xIB4vFXGyzcQbyi
+lRcTY1/GIoHx08id6Pu6WRcIueICepKRCENnwpbZmFgG4ZXiAHzACngN6vWdCVgVS9K/B1e8NPw
rShKSA6yieBr8H5KDGaQKYDyVSikp53DekE7b8fH5BzAD49j9DQFiAUi5Vtg2G0XrS/chw1MhR9w
K+GlLlvBfsvFt6QVPIZucLyqOuTlJuCPCX5XASDgl8YQoAX4M7i0frQV2jZYCFsDNFgwvAduRTsp
/4uYRxiao+npegtgpDhMLPwwN4vxRp1y0seJSYvifJQruP203QNPCi3q1SPof0DVqhSJZfH6ozxZ
54i/MHK8mvzBwfkGyYQuQOcBA9Nb1G/yVYEXpt6tiB/98L6IoG22yVYvtkEpDgIi2xcefvIt1ASu
vsRG624RC9QKIDziN2MZ7oMArSXesY2fMAvIUe4/kt96Y+Acw8y9BV5fg9pdAOtDSvb9N0DSWn54
AV6MxhggPsAF4mglP+Sg89USIFIDeBtuYmd8mbbq0Ne+KA3DY5eM9brtzu24Q7f/FgZhfpdOFVqB
6IMHHmPvHx2wLucCPxa2SNyjqQeg7Et38nFwN2Gt25/Yl9Zo1Lqd/PSOPqSLdyaSVYQVoVEGkpY9
Iv94ICP8BXi4nVH7IxRoXXV73clPDFBz053cdsZjdjMYsRYbtkaTbvuu1xqx4d1oOBh3SNZ0F4Rh
G7gSP14WCkuQHANxFWxMFLoShfjZDPy+J4B4gHYQkZE0KPkcO5lBOuiNgPWI17+h6AMBqev4H7g5
BMQXdODgn/8bL5MaEA==
===END CRASH DUMP===

**Comment by GameHerobrine** [comment]
> Festival Crash Dump Mon Jul 28 00:25:46 CDT 2025
> 
> Error: Uncaught Error: Call to undefined method pocketmine\level\generator\GeneratorRegisterTask::getTerminationInfo() in C:\Users\epics\Downloads\Festival-main (2)\Festival-main\src\pocketmine\scheduler\AsyncPool.php:155 File: /src/pocketmine/scheduler/AsyncPool Line: 155 Type: E_ERROR
> 
> Code: [146] foreach($this->tasks as $task){ [147] if($task->isGarbage() and !$task->isRunning()){ [148] [149] if(!$task->hasCancelledRun()){ [150] $task->onCompletion($this->server); [151] } [152] [153] $this->removeTask($task); [154] }elseif($task->isTerminated()){ [155] $info = $task->getTerminationInfo(); [156] $this->removeTask($task, \true); [157] $this->server->getLogger()->critical("Could not execute asynchronous task " . (new \ReflectionClass($task))->getShortName() . ": " . $info["message"]); [158] $this->server->getLogger()->critical("On ".$info["scope"].", line ".$info["line"] .", ".$info["function"]."()"); [159] } [160] } [161] [162] Timings::$schedulerAsyncTimer->stopTiming(); [163] } [164] } [165]
> 
> Backtrace: #0 (): pocketmine\Server->crashDump()
> 
> Festival version: 1.0 #0 [Protocol 27; API 1.12.0] Git commit: 0000000000000000000000000000000000000000 uname -a: Windows NT EPICSAURUS 10.0 build 26100 (Windows 10) AMD64 PHP Version: 8.0.28 Zend version: 4.0.28 OS : WINNT, win
> 
> Loaded plugins:


this crash is caused by pthreads3 not having needed method, should be fixed in https://github.com/freehij/Festival/commit/2ba393a286d305513c065b00695a76e0b3a13163

**Comment by EPICSAURUSS** [comment]
The server still crashes and actually doesnt create a crash log when it does. You have to check server logs itself to see the crash

<img width="855" height="697" alt="Image" src="https://github.com/user-attachments/assets/18ffc425-8e72-48cf-9f47-6692e383d0be" />
